### ISSUE TITLE
With the recent integration of Plumed support, the code does not compile without Plumed

### ISSUE THREAD

**Issue by Honza-R** [dftbplus/dftbplus#343]
The latest version (commit 81c0647 which added Plumed) does not compile even when the Plumed integration is disabled in the config file. In main.F90, the Plumed-related code is not closed in preprocessor conditions that would disable it.

**Comment by aradi** [comment]
Probably, I messed up something... But on my laptop (the only thing I have accessible at the moment), I can build  without plumed without any problems. Do you get any specific error? The code in main.F90 must not be guarded by preprocessor pragmas, as we generate stub functions in plumed.F90 in case the code is built without plumed.

**Comment by Honza-R** [comment]
When I compile the code as I fetched it, I get the following messages:

```[ 10%] Building Fortran object prog/dftb+/CMakeFiles/dftbplus.dir/lib_dftbplus/main.f90.o
/home/rezac/bin/DFTB+github/dftbplus/_build/prog/dftb+/lib_dftbplus/main.f90(4850): error #6285: There is no matching specific subroutine for this generic subroutine call.   [PLUMEDGLOBALCMDPTR]
    call plumedGlobalCmdPtr("setForces", derivs)
---------^
/home/rezac/bin/DFTB+github/dftbplus/_build/prog/dftb+/lib_dftbplus/main.f90(4852): error #6285: There is no matching specific subroutine for this generic subroutine call.   [PLUMEDGLOBALCMDPTR]
    call plumedGlobalCmdPtr("setPositions", coord0)
---------^
/home/rezac/bin/DFTB+github/dftbplus/_build/prog/dftb+/lib_dftbplus/main.f90(4853): error #6285: There is no matching specific subroutine for this generic subroutine call.   [PLUMEDGLOBALCMDPTR]
    call plumedGlobalCmdPtr("setMasses", mass)
---------^
/home/rezac/bin/DFTB+github/dftbplus/_build/prog/dftb+/lib_dftbplus/main.f90(4855): error #6285: There is no matching specific subroutine for this generic subroutine call.   [PLUMEDGLOBALCMDPTR]
      call plumedGlobalCmdPtr("setBox", latVecs)
-----------^
compilation aborted for /home/rezac/bin/DFTB+github/dftbplus/_build/prog/dftb+/lib_dftbplus/main.f90 (code 1)
make[2]: *** [prog/dftb+/CMakeFiles/dftbplus.dir/lib_dftbplus/main.f90.o] Error 1
make[1]: *** [prog/dftb+/CMakeFiles/dftbplus.dir/all] Error 2
make: *** [all] Error 2
```

I temporarily fixed it by commenting out all the plumed-related code in main.F90.

**Comment by aradi** [comment]
Oh, no, that's an Intel compiler bug or to be more precise, a missing F2008 feature in older Intel compiliers (Do you use Intel?)

**Comment by aradi** [comment]
It works with gfortran 7.4 and if I remember correctly, I had no problems with Intel 19 (but with several older Intel versions). Anyway, I will leave this issue open, as we have to introduce a workaround.
Could you try to change `pointer` to `target` in plumed.F90, line 176 and try, whether that works?

**Comment by Honza-R** [comment]
It's intel 19. The change of `pointer` to `target` you've suggested fixed it.

**Comment by stephethier** [comment]
Can you please commit/pull this fix? I'm also using Intel 19 and encountering the same issue.
Thanks!

**Comment by bhourahine** [comment]
See  PR #345 for the applied fix.

**Comment by aradi** [comment]
It's on master now, see commit a9329e7.
